// Generates src/styles/tokens.generated.css from src/styles/tokens.ts.  Usage: npm run tokens
import { writeFileSync } from 'node:fs';
import { categoryColors, palette, semantic, shape, typography } from '../src/styles/tokens.ts';

export function buildCss(): string {
  const lines: string[] = [];
  lines.push('/* GENERATED by `npm run tokens` from src/styles/tokens.ts. Do not edit by hand. */', '');
  lines.push('/* Runtime variables. Semantic ones are what a tenant overrides (see src/lib/tenant/theme.ts). */', ':root {');
  for (const [k, v] of Object.entries(palette)) lines.push(`  --${k}: ${v};`);
  for (const [k, v] of Object.entries(semantic)) lines.push(`  --${k}: ${v};`);
  for (const [k, v] of Object.entries(categoryColors)) lines.push(`  --cat-${k}: ${v.bg};`, `  --cat-${k}-fg: ${v.fg};`);
  for (const [k, v] of Object.entries(shape)) lines.push(`  --${k}: ${v};`);
  lines.push('}', '');
  lines.push('/* Tailwind v4 utilities that read the variables above at runtime (so tenant overrides work). */', '@theme inline {');
  for (const k of Object.keys(palette)) lines.push(`  --color-${k}: var(--${k});`);
  for (const k of Object.keys(semantic)) lines.push(`  --color-${k}: var(--${k});`);
  for (const k of Object.keys(categoryColors)) lines.push(`  --color-cat-${k}: var(--cat-${k});`, `  --color-cat-${k}-fg: var(--cat-${k}-fg);`);
  lines.push(`  --font-heading: ${typography['font-heading']};`, `  --font-sans: ${typography['font-sans']};`);
  lines.push('  --radius-chip: var(--radius-chip);', '  --radius-button: var(--radius-button);', '  --radius-card: var(--radius-card);', '  --radius-pill: var(--radius-pill);');
  lines.push('  --shadow-card: var(--shadow-card);', '}', '');
  return lines.join('\n');
}

if (import.meta.url === `file://${process.argv[1]}`) {
  writeFileSync(new URL('../src/styles/tokens.generated.css', import.meta.url), buildCss());
  console.log('wrote src/styles/tokens.generated.css');
}
